package com.davidgrath.expensetracker.di

import com.davidgrath.expensetracker.ui.addtransaction.AddDetailedTransactionActivityInstrumentedTest
import com.davidgrath.expensetracker.ui.addtransaction.AddDetailedTransactionOtherDetailsFragmentInstrumentedTest
import com.davidgrath.expensetracker.ui.main.MainActivityInstrumentedTest
import com.davidgrath.expensetracker.ui.main.statistics.StatisticsFilterActivityInstrumentedTest
import com.davidgrath.expensetracker.ui.main.statistics.StatisticsFragmentInstrumentedTest
import com.davidgrath.expensetracker.ui.transactiondetails.TransactionDetailsActivityInstrumentedTest
import dagger.Component
import javax.inject.Singleton

@Singleton
@Component(modules = [InstrumentedTestModule::class])
interface InstrumentedTestComponent: MainComponent {
    fun inject(addDetailedTransactionActivityInstrumentedTest: AddDetailedTransactionActivityInstrumentedTest)
    fun inject(mainActivityInstrumentedTest: MainActivityInstrumentedTest)
    fun inject(addDetailedTransactionOtherDetailsFragmentInstrumentedTest: AddDetailedTransactionOtherDetailsFragmentInstrumentedTest)
    fun inject(transactionDetailsActivityTest: TransactionDetailsActivityInstrumentedTest)
    fun inject(statisticsFragmentInstrumentedTest: StatisticsFragmentInstrumentedTest)
    fun inject(statisticsFilterActivityInstrumentedTest: StatisticsFilterActivityInstrumentedTest)
}